"""Init tables

Revision ID: 5437993c525e
Revises: 
Create Date: 2024-04-11 19:24:31.679982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5437993c525e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
        sa.Column('file_type', sa.Enum('audio', 'image', 'video', name='filetype'), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('tg_id', sa.String(), nullable=True),
        sa.Column('main_tag', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('code', sa.String(length=4), nullable=False),
        sa.Column('nat_name', sa.String(length=256), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_table('user',
        sa.Column('tg_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=256), nullable=False),
        sa.Column('language_id', sa.Integer(), nullable=True),
        sa.Column('language_to_learn_id', sa.Integer(), nullable=True),
        sa.Column('last_session', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['language_to_learn_id'], ['language.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tg_id'),
        sa.UniqueConstraint('username')
    )
    op.create_table('card',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('translation', sa.String(), nullable=False),
        sa.Column('example', sa.String(), nullable=True),
        sa.Column('group', sa.SmallInteger(), server_default='0', nullable=False),
        sa.Column('last_show', sa.DateTime(), nullable=True),
        sa.Column('text_language_id', sa.Integer(), nullable=False),
        sa.Column('translation_language_id', sa.Integer(), nullable=False),
        sa.Column('audio_id', sa.Integer(), nullable=True),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.CheckConstraint('"group" >= 0', name='check_group_positive'),
        sa.ForeignKeyConstraint(['audio_id'], ['file.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['image_id'], ['file.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['text_language_id'], ['language.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['translation_language_id'], ['language.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('user')
    op.drop_table('language')
    op.drop_table('file')
    # ### end Alembic commands ###
